DongHoNam/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Controllers
{
    public class KhachHangController : Controller
    {
        WatchDB db = new WatchDB();
        // GET: KhachHang
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(KhachHangDangKyModelView KH)
        {
            if(ModelState.IsValid)
            {
                if(db.KHACHHANGs.SingleOrDefault(x=>x.EMAIL==KH.EMAIL)!=null)
                {
                    ModelState.AddModelError("", "Đã tồn tại email");
                    return View();
                }
                KHACHHANG nKH = new KHACHHANG();
                nKH.EMAIL = KH.EMAIL;
                nKH.HOTEN = KH.HOTEN;
                nKH.SDT = KH.SDT;
                nKH.PASSWORD = KH.PASSWORD;
                // LƯU TRÊN CSDL
                db.KHACHHANGs.Add(nKH);
                db.SaveChanges();
                // Luu vao session
                Session["KH"] = nKH;
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(KhachHangDangNhapModelView KH)
        {
            if(ModelState.IsValid)
            {
                KHACHHANG nKH = db.KHACHHANGs.SingleOrDefault(x => x.EMAIL == KH.EMAIL && x.PASSWORD == KH.PASSWORD);
                if (nKH != null)
                {
                    Session["KH"] = nKH;
                    return RedirectToAction("Index", "SanPham");
                }
                else
                    ModelState.AddModelError("", "Đăng nhập thất bại. Tên đăng nhập hoặc mật khảu chưa đúng");
            }
            return View();
        }
        public ActionResult DangXuat()
        {
            Session.Remove("KH");
            return RedirectToAction("Index", "Home");
        }
    }
}

DongHoNam/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Controllers
{
    public class SanPhamController : Controller
    {
        WatchDB db = new WatchDB();
        // GET: SanPham
        public ActionResult Index(int ?page, int ?ID_Loai, int ?ID_ThuongHieu, string search="")
        {
            
           
            var count = db.SANPHAMs.ToList().Count();
            int pageSize = 12;
            int pageNumber = page ?? 1;
            var pageMax = count / pageSize + (count%pageSize==0?0:1);
            ViewBag.pageMax = pageMax;
            ViewBag.pageNumber = pageNumber;
            ViewBag.Tieude = "Danh sách sản phẩm";
            var dsSANPHAM = db.SANPHAMs.OrderBy(x=>x.MASP).Skip((pageNumber-1)*pageSize).Take(pageSize).ToList();
            if (ID_Loai!=null)
            {
                dsSANPHAM = db.SANPHAMs.Where(x => x.MALOAI == ID_Loai).OrderBy(x=>x.MALOAI)
                    .Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
                ViewBag.Tieude = db.LOAIs.Find(ID_Loai).TENLOAI;
            }
            
            if (ID_ThuongHieu != null)
            {
                dsSANPHAM = db.SANPHAMs.Where(x => x.MATH == ID_ThuongHieu).OrderBy(x=>x.MATH)
                    .Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
                ViewBag.Tieude = db.THUONGHIEUx.Find(ID_ThuongHieu).TENTH;
            }
            return View(dsSANPHAM);
        }
        public ActionResult Detail(int ID_Sanpham)
        {
            WatchDB db = new WatchDB();
            var SP = db.SANPHAMs.Find(ID_Sanpham);
            return View(SP);
        }
    }
}

DongHoNam/Controllers/ThuongHieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Controllers
{
    public class ThuongHieuController : Controller
    {
        WatchDB db = new WatchDB();
        // GET: ThuongHieu
        public ActionResult Index()
        {
            List<THUONGHIEU> dsThuongHieu = null;
            dsThuongHieu = db.THUONGHIEUx.ToList();

            return View(dsThuongHieu);
        }
        public ActionResult Detail(int ID_ThuongHieu)
        {
            
            var TH = db.THUONGHIEUx.Find(ID_ThuongHieu);
            return View(TH);
        }
    }
}

DongHoNam/Views/Shared/View_MenuSP.cshtml
@using DongHoNam.Models

@{
    var db = new WatchDB();
}

    <div class="list-group " style="margin-top:20px">
        <a href="#" class="list-group-item black">
            <span class="glyphicon glyphicon-list"></span> CHỦNG LOẠI ĐỒNG HỒ
        </a>
        @foreach (var item in db.LOAIs.ToList())
    {
            <a href="@Url.Action("Index",new { ID_Loai= item.MALOAI})" class="list-group-item">
                @item.TENLOAI<span class="badge"> @item.SANPHAMs.Count </span>
            </a>
    }

    </div><br />
<div class="list-group " style="margin-top:20px">
    <a href="#" class="list-group-item black">
        <span class="glyphicon glyphicon-list"></span> CÁC THƯƠNG HIỆU
    </a>
    @foreach (var item in db.THUONGHIEUx.ToList())
    {
        <a href="@Url.Action("Index",new { ID_ThuongHieu= item.MATH})" class="list-group-item">
            @item.TENTH<span class="badge"> @item.SANPHAMs.Count </span>
        </a>
    }

</div>

DongHoNam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>    
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/Tuyetroi.js"></script>
    <script src="~/Scripts/TraCuu_home.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
  @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body> 
    
         <div class="row"  style="background-color:black">

             <div class="col-md-8 text-center" style="margin-top:15px">
                 <img src="~/Image/logo_top.png" width="300px" />

             </div>
             
             <div class="col-md-4 text-left " style="color:white;font-size:larger">
                 <div style="margin-top:15px">Hotline: <b>0853857770</b></div><br />
                 <div class="navbar navbar-white ">
                     <div class="navbar-collapse collapse">
                         @using DongHoNam.Models
                         @{ 
                             KHACHHANG kh = (KHACHHANG)Session["KH"];
                         }
                         @if (kh == null)
                         {
                         <ul class="nav navbar-nav">
                             <li><a href="@Url.Action("DangKy","KhachHang")"><span class="glyphicon glyphicon-user"> Đăng ký</span></a> </li>
                             
                             <li><a href="@Url.Action("DangNhap","KhachHang")"><span class="glyphicon glyphicon-log-in"> Đăng nhập</span></a></li>
                         </ul>
                         }
                         else
                         {
                            <ul class="nav navbar-nav">
                                <li><a> @kh.HOTEN</a> </li>

                                <li><a href="@Url.Action("DangXuat","KhachHang")"><span class="glyphicon glyphicon-log-out"> Đăng xuất</span></a></li>
                            </ul>
                         }

                     </div>
                 </div>
             </div> 
         </div>
             
       <div class="navbar navbar-black navbar-stiky-top" style="background-color:white">            
        <div class="navbar-collapse collapse container" >
            <b>

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sản phẩm", "Index", "SanPham")</li>
                    <li>@Html.ActionLink("Thương hiệu", "Index", "ThuongHieu")</li>
                    <li>@Html.ActionLink("Giới thiệu", "GioiThieu", "Home")</li>
                    <li>@Html.ActionLink("Giỏ hàng", "ViewCart", "GioHang")</li>
                </ul>
            </b>
            <form class="navbar-form text-right container">
                <div class="form-group">
                    <input onkeyup="loadSP(1)" type="text" id="search" class="form-control" placeholder="Tên sản phẩm..." name="search"  />
                </div>
                <button type="submit" class="btn btn-black"><i class="glyphicon glyphicon-search"></i>Tìm</button>
            </form>
        </div>
    </div>


    <div class="body-content">
    
        <div style="min-height:1000px">
            
            @if (Session["TB"]!= null)
            {
                <script language="javascript" type="text/javascript">
                    alert('Đơn hàng của bạn đã được tiếp nhận. Cảm ơn bạn đã đặt hàng \n Đơn hàng sẽ được giao đến bạn trong vòng 2-5 ngày');
                </script>
                Session.Remove("TB");
            }
            <div id="search_home">
                @RenderBody()
            </div>
        </div>
    
            <hr />
            <footer>
                <div style="background-color:black;color:darkgray" class="text-center">
                    <p>&copy; @DateTime.Now.Year - Fourmen Watch</p>
                    <p><b>Địa chỉ:</b> 67D Phú Mỹ - Phường 22 - Bình Thạnh - Tp.HCM</p>
                    <p><b>Email:</b>fourmenwatch@gmail.com</p>
                    <p><b>Điện thoại:</b>0853827770</p>
                </div>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>