DongHoNam/Models/THUONGHIEU.cs
namespace DongHoNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("THUONGHIEU")]
    public partial class THUONGHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUONGHIEU()
        {
            SANPHAMs = new HashSet<SANPHAM>();
        }

        [Key]
        public int MATH { get; set; }

        [Required]
        [StringLength(50)]
        public string TENTH { get; set; }

        [Required]
        [StringLength(50)]
        public string QUOCGIA { get; set; }

        public int NAMTL { get; set; }

        [Required]
        [StringLength(50)]
        public string LOGO { get; set; }

        [StringLength(256)]
        public string MOTA { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}

DongHoNam/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Controllers
{
    public class SanPhamController : Controller
    {
        WatchDB db = new WatchDB();
        // GET: SanPham
        public ActionResult Index(int ?page, int ?ID_Loai, int ?ID_ThuongHieu, string search="")
        {
            
           
            var count = db.SANPHAMs.ToList().Count();
            int pageSize = 12;
            int pageNumber = page ?? 1;
            var pageMax = count / pageSize + (count%pageSize==0?0:1);
            ViewBag.pageMax = pageMax;
            ViewBag.pageNumber = pageNumber;
            ViewBag.Tieude = "Danh sách sản phẩm";
            var dsSANPHAM = db.SANPHAMs.OrderBy(x=>x.MASP).Skip((pageNumber-1)*pageSize).Take(pageSize).ToList();
            if (ID_Loai!=null)
            {
                dsSANPHAM = db.SANPHAMs.Where(x => x.MALOAI == ID_Loai).OrderBy(x=>x.MALOAI)
                    .Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
                ViewBag.Tieude = db.LOAIs.Find(ID_Loai).TENLOAI;
            }
            
            if (ID_ThuongHieu != null)
            {
                dsSANPHAM = db.SANPHAMs.Where(x => x.MATH == ID_ThuongHieu).OrderBy(x=>x.MATH)
                    .Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
                ViewBag.Tieude = db.THUONGHIEUx.Find(ID_ThuongHieu).TENTH;
            }
            return View(dsSANPHAM);
        }
        public ActionResult Detail(int ID_Sanpham)
        {
            WatchDB db = new WatchDB();
            var SP = db.SANPHAMs.Find(ID_Sanpham);
            return View(SP);
        }
    }
}

DongHoNam/Controllers/ThuongHieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Controllers
{
    public class ThuongHieuController : Controller
    {
        WatchDB db = new WatchDB();
        // GET: ThuongHieu
        public ActionResult Index()
        {
            List<THUONGHIEU> dsThuongHieu = null;
            dsThuongHieu = db.THUONGHIEUx.ToList();

            return View(dsThuongHieu);
        }
        public ActionResult Detail(int ID_ThuongHieu)
        {
            
            var TH = db.THUONGHIEUx.Find(ID_ThuongHieu);
            return View(TH);
        }
    }
}

DongHoNam/Views/ThuongHieu/Detail.cshtml
@model DongHoNam.Models.THUONGHIEU
@{
    ViewBag.Title = "Detail";
}
<div class="container panel-primary" style="margin-top:5px">
    <div class="text-center panel-heading"><h3>@Model.TENTH </h3></div>
    <div class="row panel-body">
        <div class="text-center col-md-7"><img src="~/image-Thuonghieu/@Model.LOGO" style="max-width:650px"/></div>
            <div class="col-md-5" style="font-size:medium">
            
                <div class="text-left"><b>Năm thành lập:</b> @Model.NAMTL</div>
                <div class="text-left"><b>Quốc gia:</b> @Model.QUOCGIA</div>
                <div class="text-left"><b>Mô tả:</b> @Model.MOTA</div> <br /> 
                <div><a class="btn btn-black" href="@Url.Action("Index","Home")">Trang chủ</a></div>           
            </div>
            </div>
    </div>

DongHoNam/Views/ThuongHieu/Index.cshtml
@model IEnumerable<DongHoNam.Models.THUONGHIEU>
@{
    ViewBag.Title = "Index";
}

<div class="container panel-primary" style="margin-top:5px">
    <div class="text-center panel-heading"><h3>Danh sách các thương hiệu </h3></div>
    <div class="row panel-body">
        @foreach (var item in Model)
        {
            <div class="col-md-3" style="margin-top:50px;height:300px">
                
                <div style="height:150px">
               
                    <a href="@Url.Action("Detail","ThuongHieu",new { ID_ThuongHieu=item.MATH})">
                        <img src="~/image-Thuonghieu/@item.LOGO" width="150px"/>
                    </a>
                </div><br />
                
                 <div ><b>Năm thành lập: </b>@item.NAMTL</div>
                <div><b>Quốc gia: </b>@item.QUOCGIA</div>   
                <a class="btn btn-black" href="@Url.Action("Index","SanPham",new { ID_ThuongHieu=item.MATH})">Các sản phẩm</a>        
                    
                </div>






           
        }
    </div>
</div>