DongHoNam/Areas/Admin/Controllers/ADDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Areas.Admin.Controllers
{
    [Authorize]
    public class ADDonHangController : Controller
    {
        // GET: Admin/ADDon
        WatchDB db = new WatchDB();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult getALL()
        {
            var THs = db.DONHANGs.Select(x => new { x.MADH, KHACHHANG = x.KHACHHANG.HOTEN, NGAYDAT = x.NGAYDAT.ToString(), x.TRANGTHAI, x.DIACHINHAN});
            return Json(THs, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult DoiTrangThai(int ID)
        {
            DONHANG dh = db.DONHANGs.Find(ID);
            if (dh.TRANGTHAI)
                dh.TRANGTHAI = false;
            else
                dh.TRANGTHAI = true;
            db.Entry(dh).State = System.Data.Entity.EntityState.Modified;
           int kq= db.SaveChanges();
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int ID)
        {
            var dh = db.DONHANGs.Find(ID);
            
            db.DONHANGs.Remove(dh);
            int kq = db.SaveChanges();            
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getbyID(int ID)
        {
            var ctdh = db.CTDONHANGs.Where(x => x.MADH == ID).Select(x => new
            {
                x.MADH,
                x.MASP,
                TENSP = x.SANPHAM.TENSP,
                x.SANPHAM.GIA,
                HINH = x.SANPHAM.HINH,
                SL = x.SOLUONG,
                x.THANHTIEN
            });
            return Json(ctdh,JsonRequestBehavior.AllowGet);
        }
    }
}

DongHoNam/Areas/Admin/Controllers/ADHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DongHoNam.Models;

namespace DongHoNam.Areas.Admin.Controllers
{
    
    public class ADHomeController : Controller
    {
        WatchDB db = new WatchDB();
        // GET: Admin/Default
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.KhachHang = db.KHACHHANGs.Count();
            ViewBag.SanPham = db.SANPHAMs.Count();
            ViewBag.DonHang = db.DONHANGs.Count();
            ViewBag.DoanhThu = db.DONHANGs.Sum(x => x.TONG);

            var dsDH = db.DONHANGs.OrderByDescending(x => x.NGAYDAT).Take(10);
            return View(dsDH);
        }
    }
}

DongHoNam/Areas/Admin/Controllers/ADSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using DongHoNam.Models;

namespace DongHoNam.Areas.Admin.Controllers
{
    [Authorize]
    public class ADSanPhamController : Controller
    {
        // GET: Admin/ADThuongHieu
        WatchDB db = new WatchDB();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GETALL(string str="")
        {
            var SPs = db.SANPHAMs.Select(x => new
                    {
                        x.MASP,
                        x.TENSP,
                        x.HINH,
                        x.GIA,
                        x.MALOAI,
                        x.MATH,
                        NGAYNHAP = x.NGAYNHAP.ToString()
                    });
            if (str != null && str != "")
            {
                 SPs = db.SANPHAMs.Where(x=>x.TENSP.ToLower().Contains(str.ToLower()))
                    .Select(x => new
                {
                    x.MASP,
                    x.TENSP,
                    x.HINH,
                    x.GIA,
                    x.MALOAI,
                    x.MATH,
                    NGAYNHAP = x.NGAYNHAP.ToString()
                });
            }

            return Json(SPs, JsonRequestBehavior.AllowGet);
        }
       

        [HttpPost]
        public ActionResult Add(SANPHAM SP)
        {


            db.SANPHAMs.Add(SP);
            int kq = db.SaveChanges();
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Edit(SANPHAM SP)
        {


            db.Entry(SP).State = EntityState.Modified;
            int kq = db.SaveChanges();
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int ID)
        {
            var SP = db.SANPHAMs.Find(ID);
            var path = Server.MapPath("~/image-sanpham/" + SP.HINH);
            db.SANPHAMs.Remove(SP);
            int kq = db.SaveChanges();
            if (System.IO.File.Exists(path))
                System.IO.File.Delete(path);
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getbyID(int ID)
        {
            var SP = db.SANPHAMs.Find(ID);
            var kq = new {
                MASP =SP.MASP,
                TENSP =SP.TENSP,
                TENTH=SP.THUONGHIEU.TENTH,
                XUATXU=SP.THUONGHIEU.QUOCGIA,
                NGAY =SP.NGAYNHAP.Day,
                THANG =SP.NGAYNHAP.Month,
                NAM =SP.NGAYNHAP.Year,
                NGAYNHAP=SP.NGAYNHAP,
                MATh= SP.MATH,
                MALoai =SP.MALOAI,
                MOTA =SP.MOTA,
                HINH=SP.HINH,
                GIA =SP.GIA,GIAFORMAT=SP.GIA.ToString("# ### ##0"),
                MAU =SP.MAUSAC,
                CHATLIEU=SP.CHATLIEU,NANGLUONG=SP.NANGLUONG,CHONGNUOC=SP.CHONGNUOC
            };
            return Json(kq, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult LuuAnh()
        {
            HttpPostedFileBase HINHSP = Request.Files[0];
            //Upload hinh

            if (HINHSP.ContentLength > 0 && HINHSP != null)
            {
                string filename = HINHSP.FileName;
                if (filename.Length > 45)
                    filename = filename.Substring(filename.Length - 45, 45);

                var path = Server.MapPath("~/image-sanpham/" + filename);
                HINHSP.SaveAs(path);
            }
            return Json(HINHSP.FileName, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getAllLoai()
        {
            var kq = db.LOAIs.Select(x => new { x.MALOAI, x.TENLOAI });
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getAllTH()
        {
            var kq = db.THUONGHIEUx.Select(x => new { x.MATH, x.TENTH});
            return Json(kq, JsonRequestBehavior.AllowGet);
        }
    }
}

DongHoNam/Areas/Admin/Views/Shared/_LayoutAD.cshtml
<!DOCTYPE html>
<html>
<head>
    <script src="~/Scripts/Tuyetroi.js"></script>  


    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
      
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="row navbar navbar-fixed-top" style="background-color:black">
        <div class="col-md-8 text-center" style="margin-top:15px">
            <img src="~/Image/logo_top.png" style="width:300px" />
        </div>
        <div class="col-md-4">
            @if (@User.Identity.Name.Length >0)
            {
            <div class="navbar navbar-white ">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a>Chào: @User.Identity.Name</a> </li>

                        <li><a href="@Url.Action("Logout", "Account")"><span class="glyphicon glyphicon-log-out"> Đăng xuất</span></a></li>
                    </ul>
                </div>
            </div>
            }
        </div>


    </div>

            <div class="row" style="margin-top:175px">
                <div class="col-md-3 navbar-stiky-top" style="top:170px">
                    <div class="list-group">
                        <a href="#" class="list-group-item black">
                            <span class="glyphicon glyphicon-tower"></span> ADMINTRATOR
                        </a>

                        <a href="@Url.Action("Index","ADHome")" class="list-group-item">Trang chủ</a>
                        <a href="@Url.Action("Index","ADLoaiSanPham")" class="list-group-item">Quản lý loại đồng hồ</a>
                        <a href="@Url.Action("Index","ADThuongHieu")" class="list-group-item">Quản lý thương hiệu</a>
                        <a href="@Url.Action("Index","ADSanPham")" class="list-group-item">Quản lý đồng hồ</a>
                        <a href="@Url.Action("Index","ADDonHang")" class="list-group-item">Quản lý đơn hàng</a>


                    </div>
                </div>





                <div style="min-height:700px;" class="col-md-9 container  body-content">
                    @RenderBody()
                </div>

                <hr />

            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>